"""Deterministic Markdown rendering and atomic archival."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from swing_copilot.report.daily_brief import format_sizing

if TYPE_CHECKING:
    from swing_copilot.models import RunStatus
    from swing_copilot.report.daily_brief import BriefCandidate, DailyBrief
    from swing_copilot.storage.paper_records import TradeDecisionRecord

_DISCLAIMER = "本レポートは情報提供のみを目的とし、投資助言ではありません。最終判断は自身で行ってください。"
DECISIONS_START = "<!-- decisions:start -->"
DECISIONS_END = "<!-- decisions:end -->"


def render_markdown(brief: DailyBrief, status: RunStatus) -> str:
    """Render a generated, human-readable audit snapshot."""
    lines = [
        "<!-- Generated by swing-copilot; DuckDB is the source of truth. -->",
        "",
        f"# Swing Copilot — {brief.run_date.isoformat()}",
        "",
        f"- Status: `{status.value}`",
        f"- Run ID: `{brief.run_id}`",
        f"- Generated at: `{brief.generated_at.isoformat()}`",
        "",
        "## Market",
        "",
        "| Symbol | Value | Change |",
        "|---|---:|---:|",
    ]
    lines.extend(
        f"| {item.label} | {_number(item.value)} | {_percent(item.pct_change)} |"
        for item in brief.market
    )
    lines.extend(
        [
            "",
            "## Candidates",
            "",
            "| Rank | Symbol | Close | Change | RSI14 | Score | Signals | Risk | Shares | Stop |",
            "|---:|---|---:|---:|---:|---:|---|---|---:|---:|",
        ]
    )
    lines.extend(
        "| "
        + " | ".join(
            (
                str(candidate.rank),
                candidate.symbol,
                _money(candidate.close),
                _percent(candidate.pct_change),
                _number(candidate.rsi14, digits=1),
                _number(candidate.score, digits=3),
                ", ".join(candidate.signals) or "-",
                candidate.risk.status,
                format_sizing(candidate.risk),
                _money(candidate.risk.stop_price),
            )
        )
        + " |"
        for candidate in brief.candidates
    )
    for candidate in brief.candidates:
        lines.extend(_candidate_section(candidate))
    lines.extend(["", "## 落選サマリ", ""])
    if brief.rejection_counts:
        lines.extend(["| reason_code | 件数 |", "|---|---:|"])
        lines.extend(
            f"| {item.reason_code} | {item.count} |" for item in brief.rejection_counts
        )
    else:
        lines.append("該当なし(0件)")
    if brief.notices:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {notice}" for notice in brief.notices)
    lines.extend(
        [
            "",
            "## Decisions",
            "",
            DECISIONS_START,
            "_No decisions recorded._",
            DECISIONS_END,
        ]
    )
    lines.extend(["", "---", "", _DISCLAIMER, ""])
    return "\n".join(lines)


def write_markdown_report(
    brief: DailyBrief, status: RunStatus, output_dir: str | Path
) -> Path:
    """Write a run-ID archive and `latest.md` using atomic replacement."""
    root = Path(output_dir)
    dated_dir = root / brief.run_date.isoformat()
    dated_dir.mkdir(parents=True, exist_ok=True)
    content = render_markdown(brief, status)
    report_path = dated_dir / f"{brief.run_id}.md"
    _atomic_write(report_path, content)
    _atomic_write(root / "latest.md", content)
    return report_path


def update_markdown_decisions(
    report_path: Path, decisions: list[TradeDecisionRecord]
) -> None:
    """Refresh only the generated decision block from canonical DuckDB rows."""
    content = report_path.read_text(encoding="utf-8")
    if content.count(DECISIONS_START) != 1 or content.count(DECISIONS_END) != 1:
        msg = f"generated decision markers missing or duplicated in {report_path}"
        raise ValueError(msg)
    before, remainder = content.split(DECISIONS_START, maxsplit=1)
    _old, after = remainder.split(DECISIONS_END, maxsplit=1)
    body = _render_decisions(decisions)
    _atomic_write(
        report_path,
        f"{before}{DECISIONS_START}\n{body}\n{DECISIONS_END}{after}",
    )


def _render_decisions(decisions: list[TradeDecisionRecord]) -> str:
    if not decisions:
        return "_No decisions recorded._"
    lines = [
        "| Symbol | Strategy | Decision | Fill | Reason |",
        "|---|---|---|---:|---|",
    ]
    for record in decisions:
        fill = (
            f"${record.virtual_fill_price:,.2f}"
            if record.virtual_fill_price is not None
            else "-"
        )
        reason = (record.reason_memo or "-").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {record.symbol} | {record.strategy_key} | {record.decision} | "
            f"{fill} | {reason} |"
        )
    return "\n".join(lines)


def _candidate_section(candidate: BriefCandidate) -> list[str]:
    lines = [
        "",
        f"## {candidate.symbol}",
        "",
        f"- Company: {candidate.company_name or 'N/A'}",
        f"- LLM: {candidate.llm.conclusion}",
        f"- Fundamentals: PER {candidate.fundamentals.per}, FCF {candidate.fundamentals.fcf}, "
        f"Equity ratio {candidate.fundamentals.equity_ratio}, EPS {candidate.fundamentals.eps}",
    ]
    lines.extend(f"- Risk: {reason}" for reason in candidate.risk.reasons)
    lines.extend(f"- Warning: {warning}" for warning in candidate.risk.warnings)
    lines.extend(_score_breakdown_section(candidate))
    if candidate.llm.facts:
        lines.extend(["", "### Facts", ""])
        lines.extend(f"- {fact}" for fact in candidate.llm.facts)
    if candidate.llm.risk_flags:
        lines.extend(["", "### LLM risk flags", ""])
        lines.extend(f"- {flag}" for flag in candidate.llm.risk_flags)
    if candidate.llm.sources:
        lines.extend(["", "### Sources", ""])
        lines.extend(
            f"- [{source.source_id}]({source.url})" for source in candidate.llm.sources
        )
    lines.extend(_past_decisions_section(candidate))
    return lines


def _past_decisions_section(candidate: BriefCandidate) -> list[str]:
    """REQ-008: 過去判断 subsection.

    Omitted entirely (no heading) when empty, matching this file's
    established style for optional per-candidate subsections (Facts/LLM
    risk flags/Sources above).
    """
    if not candidate.past_decisions:
        return []
    lines = [
        "",
        "### 過去判断",
        "",
        "| Date | Decision | Reason | 実現損益率 |",
        "|---|---|---|---:|",
    ]
    for past in candidate.past_decisions:
        reason = (past.reason_memo or "-").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {past.run_date.isoformat()} | {past.decision} | {reason} | "
            f"{_percent(past.realized_return_pct)} |"
        )
    return lines


def _score_breakdown_section(candidate: BriefCandidate) -> list[str]:
    """REQ-008: a per-candidate table of the composite score's weighted components."""
    if (
        candidate.score is None
        or candidate.score_rsi_pullback is None
        or candidate.score_trend_quality is None
        or candidate.score_liquidity is None
    ):
        return []
    return [
        "",
        "### Score breakdown",
        "",
        f"- Total: {candidate.score:.3f}",
        "",
        "| Component | Weighted value |",
        "|---|---:|",
        f"| rsi_pullback | {candidate.score_rsi_pullback:.3f} |",
        f"| trend_quality | {candidate.score_trend_quality:.3f} |",
        f"| liquidity | {candidate.score_liquidity:.3f} |",
    ]


def _atomic_write(path: Path, content: str) -> None:
    tmp_path = path.with_name(f".{path.name}.tmp")
    try:
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.replace(path)
    except OSError:
        tmp_path.unlink(missing_ok=True)
        raise


def _number(value: float | None, *, digits: int = 2) -> str:
    return "N/A" if value is None else f"{value:,.{digits}f}"


def _money(value: float | None) -> str:
    return "N/A" if value is None else f"${value:,.2f}"


def _percent(value: float | None) -> str:
    return "N/A" if value is None else f"{value:+.2%}"
