"""Deterministic Markdown rendering and atomic archival."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from swing_copilot.report.daily_brief import format_sizing

if TYPE_CHECKING:
    from swing_copilot.models import RunStatus
    from swing_copilot.pipeline.postmortem import SignalPerformanceRow
    from swing_copilot.report.daily_brief import (
        BriefCandidate,
        BriefPortfolioHeat,
        DailyBrief,
    )
    from swing_copilot.storage.paper_records import TradeDecisionRecord

_DISCLAIMER = "本レポートは情報提供のみを目的とし、投資助言ではありません。最終判断は自身で行ってください。"
DECISIONS_START = "<!-- decisions:start -->"
DECISIONS_END = "<!-- decisions:end -->"


def render_markdown(brief: DailyBrief, status: RunStatus) -> str:
    """Render a generated, human-readable audit snapshot."""
    lines = [
        "<!-- Generated by swing-copilot; DuckDB is the source of truth. -->",
        "",
        f"# Swing Copilot — {brief.run_date.isoformat()}",
        "",
        f"- Status: `{status.value}`",
        f"- Run ID: `{brief.run_id}`",
        f"- Generated at: `{brief.generated_at.isoformat()}`",
        "",
        "## Market",
        "",
        "| Symbol | Value | Change |",
        "|---|---:|---:|",
    ]
    lines.extend(
        f"| {item.label} | {_number(item.value)} | {_percent(item.pct_change)} |"
        for item in brief.market
    )
    if brief.regime is not None:
        lines.extend(
            [
                "",
                "## Market regime",
                "",
                f"- Gate: `{brief.regime.gate}`",
                f"- Distribution Day level: `{brief.regime.dd_level}`",
                f"- SPY d25: {brief.regime.spy_d25:g}; QQQ d25: {brief.regime.qqq_d25:g}",
                f"- Data quality: `{brief.regime.data_quality}`",
            ]
        )
        if brief.regime.spy_ftd_state is not None:
            lines.extend(
                [
                    f"- FTD SPY: `{brief.regime.spy_ftd_state}`{_ftd_suffix(brief.regime.spy_ftd_day_number, brief.regime.spy_ftd_quality_score)}",
                    f"- FTD QQQ: `{brief.regime.qqq_ftd_state}`{_ftd_suffix(brief.regime.qqq_ftd_day_number, brief.regime.qqq_ftd_quality_score)}",
                ]
            )
    if brief.exposure is not None:
        downgrade = (
            "（保守的降格）" if brief.exposure.is_conservatively_downgraded else ""
        )
        lines.extend(
            [
                "",
                "## Exposure Ceiling",
                "",
                f"- Verdict: `{brief.exposure.verdict}` {downgrade}",
                f"- Inputs: gate `{brief.exposure.gate}`, DD `{brief.exposure.dd_level}`",
                f"- Data quality: `{brief.exposure.data_quality}`",
            ]
        )
    if brief.circuit_breaker is not None:
        rules = ", ".join(brief.circuit_breaker.triggered_rules) or "none"
        lines.extend(
            [
                "",
                "## Circuit Breaker",
                "",
                f"- State: `{brief.circuit_breaker.state}`",
                f"- Data quality: `{brief.circuit_breaker.data_quality}`",
                f"- Triggered rules: `{rules}`",
            ]
        )
    if brief.portfolio_heat is not None:
        lines.extend(
            [
                "",
                "## Portfolio risk",
                "",
                f"- Portfolio heat: {_portfolio_heat_text(brief.portfolio_heat)}",
            ]
        )
    lines.extend(_candidates_section(brief.candidates))
    for candidate in brief.candidates:
        lines.extend(_candidate_section(candidate))
    lines.extend(["", "## 落選サマリ", ""])
    if brief.rejection_counts:
        lines.extend(["| reason_code | 件数 |", "|---|---:|"])
        lines.extend(
            f"| {item.reason_code} | {item.count} |" for item in brief.rejection_counts
        )
    else:
        lines.append("該当なし(0件)")
    lines.extend(["", "## シグナル成績（直近90日）", ""])
    if brief.signal_performance:
        lines.extend(
            [
                "| Signal | TP | FP | NEUTRAL | 的中率 | N |",
                "|---|---:|---:|---:|---:|---:|",
            ]
        )
        lines.extend(_signal_performance_row(row) for row in brief.signal_performance)
    else:
        lines.append("該当なし(0件)")
    if brief.notices:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {notice}" for notice in brief.notices)
    lines.extend(
        [
            "",
            "## Decisions",
            "",
            DECISIONS_START,
            "_No decisions recorded._",
            DECISIONS_END,
        ]
    )
    lines.extend(["", "---", "", _DISCLAIMER, ""])
    return "\n".join(lines)


def write_markdown_report(
    brief: DailyBrief, status: RunStatus, output_dir: str | Path
) -> Path:
    """Write a run-ID archive and `latest.md` using atomic replacement."""
    root = Path(output_dir)
    dated_dir = root / brief.run_date.isoformat()
    dated_dir.mkdir(parents=True, exist_ok=True)
    content = render_markdown(brief, status)
    report_path = dated_dir / f"{brief.run_id}.md"
    _atomic_write(report_path, content)
    _atomic_write(root / "latest.md", content)
    return report_path


def _portfolio_heat_text(heat: BriefPortfolioHeat) -> str:
    """Render the portfolio-heat value without adding report-level branches."""
    if heat.heat_pct is not None:
        return f"`{heat.heat_pct:.2f}% / {heat.max_heat_pct:.2f}%`"
    if heat.missing_stop_symbols:
        symbols = ", ".join(heat.missing_stop_symbols)
        return f"`not_calculable` (missing stop: {symbols})"
    return f"`not_calculable` ({heat.reason or 'unknown reason'})"


def update_markdown_decisions(
    report_path: Path, decisions: list[TradeDecisionRecord]
) -> None:
    """Refresh only the generated decision block from canonical DuckDB rows."""
    content = report_path.read_text(encoding="utf-8")
    if content.count(DECISIONS_START) != 1 or content.count(DECISIONS_END) != 1:
        msg = f"generated decision markers missing or duplicated in {report_path}"
        raise ValueError(msg)
    before, remainder = content.split(DECISIONS_START, maxsplit=1)
    _old, after = remainder.split(DECISIONS_END, maxsplit=1)
    body = _render_decisions(decisions)
    _atomic_write(
        report_path,
        f"{before}{DECISIONS_START}\n{body}\n{DECISIONS_END}{after}",
    )


def _render_decisions(decisions: list[TradeDecisionRecord]) -> str:
    if not decisions:
        return "_No decisions recorded._"
    lines = [
        "| Symbol | Strategy | Decision | Fill | Reason |",
        "|---|---|---|---:|---|",
    ]
    for record in decisions:
        fill = (
            f"${record.virtual_fill_price:,.2f}"
            if record.virtual_fill_price is not None
            else "-"
        )
        reason = (record.reason_memo or "-").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {record.symbol} | {record.strategy_key} | {record.decision} | "
            f"{fill} | {reason} |"
        )
    return "\n".join(lines)


def _candidates_section(candidates: tuple[BriefCandidate, ...]) -> list[str]:
    """P6-28: one self-contained table per P5-23 execution bucket.

    Each bucket gets its own heading, header row, separator row, and data
    rows in sequence, rather than a single table interrupted midstream by
    bucket headings -- the latter breaks Markdown table rendering because a
    heading between the header/separator and the data rows ends the table.
    """
    lines = ["", "## Candidates"]
    for bucket in ("即検討可", "様子見", "見送り"):
        bucket_candidates = [
            candidate
            for candidate in candidates
            if _execution_bucket(candidate) == bucket
        ]
        lines.extend(["", f"### {bucket}", ""])
        if not bucket_candidates:
            lines.append("該当なし")
            continue
        lines.extend(
            [
                "| Rank | Symbol | Close | Change | RSI14 | Score | Execution | Signals | Risk | Shares | Stop |",
                "|---:|---|---:|---:|---:|---:|---|---|---|---:|---:|",
            ]
        )
        lines.extend(_candidate_row(candidate) for candidate in bucket_candidates)
    return lines


def _candidate_row(candidate: BriefCandidate) -> str:
    return (
        "| "
        + " | ".join(
            (
                str(candidate.rank),
                candidate.symbol,
                _money(candidate.close),
                _percent(candidate.pct_change),
                _number(candidate.rsi14, digits=1),
                _number(candidate.score, digits=3),
                _execution_state_text(candidate),
                ", ".join(candidate.signals) or "-",
                candidate.risk.status,
                format_sizing(candidate.risk),
                _money(candidate.risk.stop_price),
            )
        )
        + " |"
    )


def _candidate_section(candidate: BriefCandidate) -> list[str]:
    lines = [
        "",
        f"## {candidate.symbol}",
        "",
        f"- Company: {candidate.company_name or 'N/A'}",
        f"- LLM: {candidate.llm.conclusion}",
        f"- Fundamentals: PER {candidate.fundamentals.per}, FCF {candidate.fundamentals.fcf}, "
        f"Equity ratio {candidate.fundamentals.equity_ratio}, EPS {candidate.fundamentals.eps}",
    ]
    lines.extend(f"- Risk: {reason}" for reason in candidate.risk.reasons)
    lines.extend(f"- Warning: {warning}" for warning in candidate.risk.warnings)
    lines.extend(f"- Warning: {warning}" for warning in candidate.risk.sizing_warnings)
    lines.extend(_score_breakdown_section(candidate))
    if candidate.llm.catalyst_quality is not None:
        # P2-12 (REQ-006/007): display-only, never feeds ranking/judgment.
        lines.append(f"- Catalyst quality: {candidate.llm.catalyst_quality}")
    if candidate.llm.is_news_near_stale:
        lines.append(
            "- Warning: ニュース分析のキャッシュがTTL間近です。再実行を検討してください。"
        )
    if candidate.llm.facts:
        lines.extend(["", "### Facts", ""])
        lines.extend(f"- {fact}" for fact in candidate.llm.facts)
    if candidate.llm.risk_flags:
        lines.extend(["", "### LLM risk flags", ""])
        lines.extend(f"- {flag}" for flag in candidate.llm.risk_flags)
    if candidate.llm.sources:
        lines.extend(["", "### Sources", ""])
        lines.extend(
            f"- [{source.source_id}]({source.url})" for source in candidate.llm.sources
        )
    lines.extend(_filing_analysis_sections(candidate))
    lines.extend(_past_decisions_section(candidate))
    return lines


def _filing_analysis_sections(candidate: BriefCandidate) -> list[str]:
    """P6-27: one identified subsection per filing analysis (type + filed date).

    Previously only the first filing analysis per symbol reached the report
    at all (`report/daily_brief.py::_llm_brief()`'s old `next(...)` lookup);
    now every filing analysis for this candidate is shown, individually
    labeled so which disclosure a fact/interpretation came from is clear.
    """
    lines: list[str] = []
    for filing in candidate.llm.filings:
        lines.extend(
            [
                "",
                f"### 開示分析: {filing.filing_type} ({filing.filed_at.isoformat()})",
                "",
            ]
        )
        if filing.is_near_stale:
            lines.append(
                "_警告: このキャッシュ済み分析はTTL間近です。再実行を検討してください。_"
            )
        lines.append(f"- Guidance direction: {filing.guidance_direction}")
        lines.extend(f"- Fact: {fact}" for fact in filing.facts)
        lines.extend(f"- Interpretation: {text}" for text in filing.interpretation)
        lines.extend(f"- Red flag: {flag}" for flag in filing.red_flags)
        lines.extend(f"- YoY change: {change}" for change in filing.yoy_changes)
        lines.extend(
            f"- Source: [{source.source_id}]({source.url})" for source in filing.sources
        )
    return lines


def _past_decisions_section(candidate: BriefCandidate) -> list[str]:
    """REQ-008: 過去判断 subsection.

    Omitted entirely (no heading) when empty, matching this file's
    established style for optional per-candidate subsections (Facts/LLM
    risk flags/Sources above).
    """
    if not candidate.past_decisions:
        return []
    lines = [
        "",
        "### 過去判断",
        "",
        "| Date | Decision | Reason | 実現損益率 |",
        "|---|---|---|---:|",
    ]
    for past in candidate.past_decisions:
        reason = (past.reason_memo or "-").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {past.run_date.isoformat()} | {past.decision} | {reason} | "
            f"{_percent(past.realized_return_pct)} |"
        )
    return lines


def _score_breakdown_section(candidate: BriefCandidate) -> list[str]:
    """REQ-008: a per-candidate table of the composite score's weighted components."""
    if (
        candidate.score is None
        or candidate.score_rsi_pullback is None
        or candidate.score_trend_quality is None
        or candidate.score_liquidity is None
    ):
        return []
    return [
        "",
        "### Score breakdown",
        "",
        f"- Total: {candidate.score:.3f}",
        "",
        "| Component | Weighted value |",
        "|---|---:|",
        f"| rsi_pullback | {candidate.score_rsi_pullback:.3f} |",
        f"| trend_quality | {candidate.score_trend_quality:.3f} |",
        f"| liquidity | {candidate.score_liquidity:.3f} |",
    ]


def _signal_performance_row(row: SignalPerformanceRow) -> str:
    """P2-11: one "シグナル成績" table row, with a `(暫定)` marker under REQ-030."""
    hit_rate = _percent(row.hit_rate)
    if row.is_preliminary:
        hit_rate += " (暫定)"
    return (
        f"| {row.signal_name} | {row.true_positive_count} | "
        f"{row.false_positive_count} | {row.neutral_count} | {hit_rate} | {row.n} |"
    )


def _atomic_write(path: Path, content: str) -> None:
    tmp_path = path.with_name(f".{path.name}.tmp")
    try:
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.replace(path)
    except OSError:
        tmp_path.unlink(missing_ok=True)
        raise


def _number(value: float | None, *, digits: int = 2) -> str:
    return "N/A" if value is None else f"{value:,.{digits}f}"


def _execution_state_text(candidate: BriefCandidate) -> str:
    """Render the code-owned P5-23 state and ATR-normalized distance."""
    if candidate.execution_distance is None:
        return f"{candidate.execution_state} (d=N/A)"
    return f"{candidate.execution_state} (d={candidate.execution_distance:.2f})"


def _execution_bucket(candidate: BriefCandidate) -> str:
    if candidate.execution_state in {"PULLBACK_ZONE", "FAIR"}:
        return "即検討可"
    if candidate.execution_state == "EXTENDED":
        return "様子見"
    return "見送り"


def _money(value: float | None) -> str:
    return "N/A" if value is None else f"${value:,.2f}"


def _percent(value: float | None) -> str:
    return "N/A" if value is None else f"{value:+.2%}"


def _ftd_suffix(day_number: int | None, score: int | None) -> str:
    values = []
    if day_number is not None:
        values.append(f"Day{day_number}")
    if score is not None:
        values.append(f"品質スコア {score}")
    return f"（{'、'.join(values)}）" if values else ""
