"""CLI-first daily brief rendering and Markdown archival contracts."""

from __future__ import annotations

from dataclasses import replace
from datetime import UTC, date, datetime
from pathlib import Path
from uuid import UUID

import pytest

from swing_copilot.models import RunStatus
from swing_copilot.report.daily_brief import (
    BriefCandidate,
    BriefFundamentals,
    BriefLlm,
    BriefMarketItem,
    BriefRejectionCount,
    BriefRisk,
    BriefSource,
    DailyBrief,
)
from swing_copilot.report.markdown_report import render_markdown, write_markdown_report
from swing_copilot.report.terminal_report import render_terminal

RUN_ID = UUID("11111111-2222-3333-4444-555555555555")


def _brief() -> DailyBrief:
    return DailyBrief(
        run_id=RUN_ID,
        run_date=date(2026, 7, 22),
        generated_at=datetime(2026, 7, 22, 12, tzinfo=UTC),
        market=(BriefMarketItem("SPY", 638.25, 0.006),),
        candidates=(
            BriefCandidate(
                rank=1,
                symbol="NVDA",
                company_name="NVIDIA Corporation",
                close=171.20,
                pct_change=0.012,
                rsi14=48.2,
                atr14=4.1,
                score=0.627,
                score_rsi_pullback=0.167,
                score_trend_quality=0.300,
                score_liquidity=0.160,
                signals=("RSI押し目",),
                fundamentals=BriefFundamentals(
                    per="41.2x", fcf="$12,000", equity_ratio="52%", eps="$4.16"
                ),
                risk=BriefRisk(
                    status="approved",
                    max_shares=12,
                    stop_price=164.80,
                    reasons=(),
                    warnings=("AMDとの相関 0.82",),
                ),
                llm=BriefLlm(
                    degraded=False,
                    conclusion="業績見通しは維持されているが規制リスクが残る",
                    facts=("売上高は前年同期比で増加した",),
                    risk_flags=("規制環境の不確実性",),
                    sources=(BriefSource("news:123", "https://example.com/news/123"),),
                ),
            ),
        ),
        notices=("FREDカレンダーを取得できませんでした",),
    )


def test_terminal_output_is_a_compact_decision_brief() -> None:
    output = render_terminal(_brief(), RunStatus.DEGRADED, width=120, color=False)

    assert "Swing Copilot" in output
    assert "2026-07-22" in output
    assert "DEGRADED" in output
    assert "NVDA" in output
    assert "171.20" in output
    assert "approved" in output
    assert "業績見通しは維持されているが規制リスクが残る" in output
    assert "FREDカレンダーを取得できませんでした" in output
    assert "<html" not in output


def test_markdown_contains_auditable_details_and_source_urls() -> None:
    output = render_markdown(_brief(), RunStatus.SUCCESS)

    assert (
        "<!-- Generated by swing-copilot; DuckDB is the source of truth. -->" in output
    )
    assert "# Swing Copilot — 2026-07-22" in output
    assert str(RUN_ID) in output
    assert "## NVDA" in output
    assert "売上高は前年同期比で増加した" in output
    assert "[news:123](https://example.com/news/123)" in output
    assert "本レポートは情報提供のみを目的とし、投資助言ではありません" in output


def test_terminal_shows_score_column_and_breakdown() -> None:
    # REQ-007
    output = render_terminal(_brief(), RunStatus.SUCCESS, width=200, color=False)

    assert "0.627" in output
    assert "rsi 0.17 / trend 0.30 / liq 0.16" in output


def test_markdown_shows_score_column_and_breakdown_table() -> None:
    # REQ-008
    output = render_markdown(_brief(), RunStatus.SUCCESS)

    assert "| 1 | NVDA |" in output
    assert "0.627" in output
    assert "### Score breakdown" in output
    assert "| rsi_pullback | 0.167 |" in output
    assert "| trend_quality | 0.300 |" in output
    assert "| liquidity | 0.160 |" in output


def _brief_without_candidates() -> DailyBrief:
    return replace(_brief(), candidates=())


def test_terminal_renders_empty_candidate_set_without_error() -> None:
    output = render_terminal(_brief_without_candidates(), RunStatus.SUCCESS, width=120)

    assert "Candidates: 0" in output
    assert "Score" in output  # header still renders


def _brief_with_rejections() -> DailyBrief:
    return replace(
        _brief(),
        rejection_counts=(
            BriefRejectionCount("FILTER_LOW_LIQUIDITY", 3),
            BriefRejectionCount("SIGNAL_RSI_NOT_MET", 1),
        ),
    )


def test_terminal_shows_rejection_summary_counts() -> None:
    # REQ-005: 落選サマリ, reason_code別件数.
    output = render_terminal(_brief_with_rejections(), RunStatus.SUCCESS, width=120)

    assert "落選サマリ" in output
    assert "FILTER_LOW_LIQUIDITY" in output
    assert "3" in output
    assert "SIGNAL_RSI_NOT_MET" in output


def test_markdown_shows_rejection_summary_table() -> None:
    output = render_markdown(_brief_with_rejections(), RunStatus.SUCCESS)

    assert "## 落選サマリ" in output
    assert "FILTER_LOW_LIQUIDITY" in output
    assert "| 3 |" in output
    assert "SIGNAL_RSI_NOT_MET" in output


def test_terminal_renders_empty_rejection_summary_without_error() -> None:
    # REQ-010 boundary: zero rejections renders a "0件" style message, no
    # exception.
    output = render_terminal(_brief(), RunStatus.SUCCESS, width=120)

    assert "落選サマリ" in output
    assert "0件" in output


def test_markdown_renders_empty_rejection_summary_without_error() -> None:
    output = render_markdown(_brief(), RunStatus.SUCCESS)

    assert "## 落選サマリ" in output
    assert "0件" in output


def test_markdown_renders_empty_candidate_set_without_error() -> None:
    output = render_markdown(_brief_without_candidates(), RunStatus.SUCCESS)

    assert "## Candidates" in output
    assert "### Score breakdown" not in output


def _brief_with_missing_score() -> DailyBrief:
    brief = _brief()
    candidate = replace(
        brief.candidates[0],
        score=None,
        score_rsi_pullback=None,
        score_trend_quality=None,
        score_liquidity=None,
    )
    return replace(brief, candidates=(candidate,))


def test_terminal_shows_na_when_score_is_missing() -> None:
    output = render_terminal(_brief_with_missing_score(), RunStatus.SUCCESS, width=200)

    assert "N/A" in output


def test_markdown_omits_breakdown_section_when_score_is_missing() -> None:
    output = render_markdown(_brief_with_missing_score(), RunStatus.SUCCESS)

    assert "### Score breakdown" not in output
    assert "N/A" in output


def test_markdown_is_written_per_run_and_latest_is_replaced(tmp_path: Path) -> None:
    path = write_markdown_report(_brief(), RunStatus.SUCCESS, tmp_path)

    assert path == tmp_path / "2026-07-22" / f"{RUN_ID}.md"
    assert path.is_file()
    assert (tmp_path / "latest.md").read_text(encoding="utf-8") == path.read_text(
        encoding="utf-8"
    )


def test_latest_replace_failure_preserves_previous_latest_and_cleans_temp(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    latest = tmp_path / "latest.md"
    latest.write_text("previous", encoding="utf-8")
    original_replace = Path.replace

    def fail_latest_replace(self: Path, target: Path) -> Path:
        if self.name == ".latest.md.tmp":
            message = "simulated latest replacement failure"
            raise OSError(message)
        return original_replace(self, target)

    monkeypatch.setattr(Path, "replace", fail_latest_replace)

    with pytest.raises(OSError, match="simulated latest replacement failure"):
        write_markdown_report(_brief(), RunStatus.SUCCESS, tmp_path)

    assert latest.read_text(encoding="utf-8") == "previous"
    assert not (tmp_path / ".latest.md.tmp").exists()
